### ISSUE TITLE
I can't seem to push minecarts even when they are on rails

### ISSUE THREAD

**Issue by JblackMC** [JblackMC/SA-Crafters#3]
Server:
Diamond

Describe the bug:
Cannot push minecraft

Describe how to make the bug happen:
Try to push minecraft

Additional info:
Reported by TheRealHitmann#6969

**Comment by JblackMC** [comment]
Investigating

**Comment by JblackMC** [comment]
Potential fix found, to test soon.

**Comment by JblackMC** [comment]
Pushed possible fix to server, needs to be tested.

**Comment by MrHan18** [comment]
Confirmation: Issue still occurs
